config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  namespace :api, { format: 'json' } do
    resources :translations, only: %i(create)
    get 'licenses', to: 'licenses#show'
    get 'usages', to: 'usages#show'
    resource :user, only: %i(show)
    resources :webhooks, only: %i(create)
    resources :checkout_sessions, only: %i(create)
    resources :subscriptions, only: %i(destroy)
  end

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    delete 'users/sign_out', to: 'devise/sessions#destroy', as: :destroy_user_session
  end
end

app/views/shared/_cancel_subscription_modal.html.erb
<div class="modal fade" id="cancel-subscription-modal" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Cancel a subscription</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        Are you sure you want to cancel a subscription?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-outline-secondary btn-no" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary btn-yes">Yes, cancel a subscription</button>
      </div>
    </div>
  </div>
</div>

app/views/shared/_sign_in_modal.html.erb
<div class="modal fade" id="sign-in-modal" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Sign in with Google</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        First of all, please sign in with Google.<br>
        <br>
        - A license key will be issued after signing in.<br>
        - This app can access email address only.<br>
        - You can sign out at any time.
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-outline-secondary btn-no" data-dismiss="modal">Cancel</button>
        <button type="button" class="btn btn-primary btn-yes">Sign in</button>
      </div>
    </div>
  </div>
</div>

app/views/shared/_sign_out_modal.html.erb
<div class="modal fade" id="sign-out-modal" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Sign out</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        Are you sure you want to sign out?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-outline-secondary btn-no" data-dismiss="modal">Cancel</button>
        <button type="button" class="btn btn-primary btn-yes">Sign out</button>
      </div>
    </div>
  </div>
</div>

app/views/shared/_stripe.html.erb
<script src='https://js.stripe.com/v3'></script>

<% if user_signed_in? %>
  <% if current_user.has_subscription? %>
    <%= javascript_tag nonce: true do %>
      $(function () {
        function disableCheckoutButton(button) {
          if (!button.data('checkout-initialized')) {
            button.data('checkout-initialized', true)
            button.attr('disabled', 'disabled')
            button.addClass('disabled')
            button.text('<%= t('.already_purchased') %>')
          }
          return false
        }

        $('.btn-checkout').each(function () {
          return disableCheckoutButton($(this))
        })

        $(document).on('click', '.btn-checkout', function () {
          return disableCheckoutButton($(this))
        })
      })
    <% end %>
  <% else %>
    <%= javascript_tag nonce: true do %>
      $(function () {
        var stripe = Stripe("<%= ENV['STRIPE_PUBLISHABLE_KEY'] %>")

        function redirectToCheckout() {
          var url = '<%= api_checkout_sessions_path %>'
          $.post(url).done(function (res) {
            stripe.redirectToCheckout({sessionId: res.session_id}).then(function (result) {
              alert(result.error.message)
            })
          }).fail(function (xhr) {
            alert(JSON.parse(xhr.responseText).message)
          })
        }

        $(document).on('click', '.btn-checkout', function () {
          redirectToCheckout()
          return false
        })
      })
    <% end %>
  <% end %>
<% else %>
  <%= javascript_tag nonce: true do %>
    $(function () {
      $(document).on('click', '.btn-checkout', function () {
        $('#sign-in-modal').modal()
        return false
      })
    })
  <% end %>
<% end %>